#!/usr/bin/env bash

domain="$1"
subdomain="$2"

if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
else
    subdomains=("$subdomain")
fi

for sub in "${subdomains[@]}"; do
    result=$(dig +short "$sub.$domain" | tail -n1)
    record_type=$(dig +short "$sub.$domain" | awk '{print $4}')
    echo "The subdomain $sub is a $record_type record and points to $result"
done

