#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "Usage: $0 <domain> [subdomain]"
    exit 1
fi

domain="$1"
subdomain="$2"

# Define an array of subdomains to check
subdomains=("www" "lb-01" "web-01" "web-02")

# Function to display DNS information for a subdomain
display_dns_info() {
    subdomain="$1"
    dig_output=$(dig "$subdomain.$domain" +short)
    
    if [ -z "$dig_output" ]; then
        echo "The subdomain $subdomain does not exist for $domain."
    else
        record_type=$(dig "$subdomain.$domain" +short -t ANY | awk 'NR==1{print $2}')
        echo "The subdomain $subdomain is a $record_type record and points to $dig_output"
    fi
}

# Check if subdomain argument is provided
if [ -z "$subdomain" ]; then
    # Display information for all subdomains
    for sub in "${subdomains[@]}"; do
        display_dns_info "$sub"
    done
else
    # Display information for the specified subdomain
    display_dns_info "$subdomain"
fi

